### PR TITLE
Added dtype numbers & more HW

### PR DESCRIPTION
**Pull request by iakashpaul**
I'm also creating an API using Truss for easier & cheaper runs on Baseten hardware suite in the another PR.

### CODE REVIEW

**Comment by chsasank** [comment]
Can you give me the links/descriptions of Truss and Baseton? Never heard of them.

**Comment by chsasank** [comment]
Thanks for the contribution. This is very extensive.

**Comment by iakashpaul** [comment]
> Can you give me the links/descriptions of Truss and Baseton? Never heard of them.

https://truss.baseten.co/welcome & https://github.com/basetenlabs/truss 

Helps quite a lot with unifying lot of local testing & deployment across serverless vendors/platforms without as much custom code/config

**Comment by chsasank** [comment]
Can you believe that 30k usd a100 is slower than 30k inr arc 770 in bf16 flops. This is next level.

**Pull request merged**
